### PR TITLE
Multi-agenda, and version upgrade/versions refactor

### PR DESCRIPTION
**Pull request by chappjc**
This contains:
1. Phase 1 (upgrade) info refactoring.
2. Implementation of multi-agenda, which includes a new `Agenda` type in web.go that embeds `dcrjson.Agenda` with other helpful fields and methods for easy use by the html template.

The new bits look like this:

image

**This is still a WIP, but please review ASAP.**  To start, it's still not clear to me how "most popular" should be understood in phase 1, and how this relates to current and next, for both block and stake versions.

### CODE REVIEW

**Comment by chappjc** [comment]
rebased.
Needs docs on a few exported things.

**Comment by alexlyp** [comment]
Cool I'll test and wait to merge for when those docs get added

**Comment by alexlyp** [comment]
Looks great, just needs that doco and it's good to go

**Comment by chappjc** [comment]
OK, very soon

**Review by alexlyp — APPROVED** [review]
OK

**Pull request merged**
