### PR TITLE
Initial Commit Theme v1

### PR DESCRIPTION
**Pull request by karamble**
This is the first Version of the new theme

It allready has the new design html files included in the directory tplhardforkv1
All needed public assets (css,js,images) are prerendered in the public/ directory, therefore all old files contained in that folder got wiped.

You can make changes as needed in the css/js/files in that new tplhardforkv1 directory and then 'grunt' render them into the 'public' folder.

If you want to use the old design, just clear the public folder and 'grunt' render the tplhardforkdemo/ directory.

The old design used the design_sketch.html view
The new design uses now the start.html view

----

Needed works:

For the Agenda List of the currently ongoing Agendas a loop is needed that goes trough the output of `getvoteinfo 4` whereas the 'latest version' problem still exists and needs a solution in the future.

Its work in progress. I branched the old version because i wish to keep that branch up and maybe host that project seperate on an own webserver, therefore i ask to not remove the design_sketch.html and tplhardforkdemo directory.

The complete grunt html render process needs work from my site. just wanted to play the ball.

Have fun.
grafik

### CODE REVIEW

**Comment by chappjc** [comment]
This helps a lot.  I'm really excited to rebase and work on top of this.

I have a pretty clear idea of how to handle the latest block and stake version issues based on discussion with davecgh and ay-p.  So I'll pick up where ay-p's PR left off with that in addition to the other stuff.

**Comment by karamble** [comment]
As for now the display has changed. The MostPopular placeholders now hold the latest Versions. I dont know when they trigger and what the threshold for them is, but i guess after a while they are detected correct (even when they are not mostPopular from their amount of appearance, i guess i need an explanation on those MostPopular treshholds). So you can now focus on the agenda-/choice itteration for the bottom part of the page. I have filled allready the first agenda-card with logics for the display switches.

**Comment by chappjc** [comment]
One initial observation I have is that the text underneath "Voting Overview" is way too small.  The diagrams to the left of that are also a bit small, looking best at about 140% zoom.  Even all the stuff below that looks really good at 110-125%.

**Review by alexlyp — APPROVED** [review]
OK

**Pull request merged**
